version: '3.8'

services:
  frontend:
    build:
      context: ./cognee-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: always

  backend:
    build:
      context: ./cognee-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - neo4j
      - chroma
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your_secure_password_here # Please change this
      - CHROMA_URL=http://chroma:8000
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Pass through from host .env file or shell
      # Add other backend environment variables if needed
      - PORT=3001
      - CHROMA_COLLECTION_NAME=cognee_main_collection
      - DEFAULT_CHAT_MODEL_NAME=gemini-pro
      - DEFAULT_EMBEDDING_MODEL_NAME=text-embedding-004

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/your_secure_password_here # Please change this
    restart: always

  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    restart: always

volumes:
  neo4j_data:
  chroma_data:
