import { Document } from '@langchain/core/documents';
import { VectorStoreRetriever } from '@langchain/core/vectorstores';
import { Chroma } from '@langchain/community/vectorstores/chroma';
import { GoogleGenerativeAIEmbeddings } from '@langchain/google-genai';
import { GEMINI_API_KEY, CHROMA_URL, CHROMA_COLLECTION_NAME as DEFAULT_COLLECTION_NAME } from '../config'; // Assuming CHROMA_COLLECTION_NAME can be a default

let embeddingsModel: GoogleGenerativeAIEmbeddings | undefined;

if (GEMINI_API_KEY) {
  embeddingsModel = new GoogleGenerativeAIEmbeddings({
    apiKey: GEMINI_API_KEY,
    modelName: 'text-embedding-004', // Consistent with llmService.ts
  });
  console.log('GoogleGenerativeAIEmbeddings initialized for vector-store.ts');
} else {
  console.warn('GEMINI_API_KEY is not set. Vector store operations requiring new embeddings will fail or use mock data if not pre-computed.');
}

function getInitializedEmbeddings(): GoogleGenerativeAIEmbeddings {
  if (!embeddingsModel) {
    if (GEMINI_API_KEY) { // Attempt re-initialization if key becomes available
        embeddingsModel = new GoogleGenerativeAIEmbeddings({
            apiKey: GEMINI_API_KEY,
            modelName: 'text-embedding-004',
        });
        console.log('Re-initialized GoogleGenerativeAIEmbeddings in vector-store.ts');
        return embeddingsModel;
    }
    throw new Error('Embeddings model not initialized. GEMINI_API_KEY is missing.');
  }
  return embeddingsModel;
}

// Helper function to get a Chroma vector store instance
// This ensures that the Chroma client is configured with the embeddings model.
async function getVectorStore(collectionName: string): Promise<Chroma> {
  const currentEmbeddings = getInitializedEmbeddings();
  if (!CHROMA_URL) {
    throw new Error('CHROMA_URL is not configured. Cannot connect to ChromaDB.');
  }

  // The Chroma constructor takes an Embeddings instance and a config object.
  // The config object includes `url` and `collectionName`.
  const chromaConfig = {
    collectionName: collectionName,
    url: CHROMA_URL,
    // collectionMetadata: { "hnsw:space": "cosine" }, // Optional: if needed, default is L2
  };

  // For adding documents, we usually pass pre-computed embeddings if doing it manually,
  // but LangChain's Chroma class can also handle embedding internally if documents are passed directly.
  // More commonly, vectorStore.addDocuments will use the embeddings object passed to its constructor.

  // Initialize Chroma. This doesn't create the collection yet if it doesn't exist with fromExistingCollection.
  // addDocuments will typically create it if it's not there.
  const vectorStore = new Chroma(currentEmbeddings, chromaConfig);
  console.log(`Chroma vector store instance configured for collection: ${collectionName} at ${CHROMA_URL}`);
  return vectorStore;
}

/**
 * Adds an array of LangChain Documents to the specified Chroma collection.
 * The documents are expected to have `pageContent` and `metadata`.
 * Embeddings will be generated by the `embeddingsModel` for these documents.
 * @param documents - Array of LangChain Documents.
 * @param collectionName - The name of the Chroma collection. Defaults to CHROMA_COLLECTION_NAME from config.
 */
export async function addDocuments(
  documents: Document[],
  collectionName: string = DEFAULT_COLLECTION_NAME
): Promise<void> {
  if (!documents || documents.length === 0) {
    console.log('No documents provided to add.');
    return;
  }
  getInitializedEmbeddings(); // Ensure embeddings model is ready

  const vectorStore = await getVectorStore(collectionName);

  try {
    console.log(`Adding ${documents.length} documents to Chroma collection '${collectionName}'...`);
    // The addDocuments method of the Chroma class will use the embeddings model
    // passed during its instantiation to generate embeddings for the documents.
    await vectorStore.addDocuments(documents);
    console.log(`Successfully added ${documents.length} documents to collection '${collectionName}'.`);
  } catch (error: any) {
    console.error(`Error adding documents to Chroma collection '${collectionName}':`, error.message, error.stack);
    throw new Error(`Failed to add documents to Chroma: ${error.message}`);
  }
}

/**
 * Creates a retriever for the specified Chroma collection.
 * @param collectionName - The name of the Chroma collection. Defaults to CHROMA_COLLECTION_NAME.
 * @param k - The number of documents to retrieve. Defaults to 5.
 * @returns A VectorStoreRetriever instance.
 */
export async function createRetriever(
  collectionName: string = DEFAULT_COLLECTION_NAME,
  k: number = 5
): Promise<VectorStoreRetriever<Chroma>> {
  getInitializedEmbeddings(); // Ensure embeddings model is ready for retriever to function if needed (e.g. query translation)

  const vectorStore = await getVectorStore(collectionName);

  console.log(`Creating retriever for Chroma collection '${collectionName}' with k=${k}.`);
  return vectorStore.asRetriever({ k });
}

console.log('vector-store.ts loaded');
